name: Basic Continuous Integration

on:
  push:
    branches: [ "setup/github-actions" ]
  pull_request:
    branches: [ "mainm" ]

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Print confirmation message
        run: echo "GitHub Actions workflow is running successfully"
